export interface PresetCurrency {
  code: string;
  name: string;
  flag: string;
  countryCode: string;
}

export const PRESET_CURRENCIES: PresetCurrency[] = [
  { code: "ZWG", name: "ZIMBABWE GOLD", flag: "🇿🇼", countryCode: "zw" },
  { code: "USD", name: "US DOLLAR", flag: "🇺🇸", countryCode: "us" },
  { code: "EUR", name: "EURO", flag: "🇪🇺", countryCode: "eu" },
  { code: "GBP", name: "POUND STERLING", flag: "🇬🇧", countryCode: "gb" },
  { code: "AED", name: "UAE DIRHAM", flag: "🇦🇪", countryCode: "ae" },
  { code: "JPY", name: "JAPANESE YEN", flag: "🇯🇵", countryCode: "jp" },
  { code: "CHF", name: "SWISS FRANC", flag: "🇨🇭", countryCode: "ch" },
  { code: "CAD", name: "CANADIAN DOLLAR", flag: "🇨🇦", countryCode: "ca" },
  { code: "AUD", name: "AUSTRALIAN DOLLAR", flag: "🇦🇺", countryCode: "au" },
  { code: "NZD", name: "NEW ZEALAND DOLLAR", flag: "🇳🇿", countryCode: "nz" },
  { code: "CNY", name: "CHINESE YUAN", flag: "🇨🇳", countryCode: "cn" },
  { code: "INR", name: "INDIAN RUPEE", flag: "🇮🇳", countryCode: "in" },
  { code: "SAR", name: "SAUDI RIYAL", flag: "🇸🇦", countryCode: "sa" },
  { code: "QAR", name: "QATARI RIYAL", flag: "🇶🇦", countryCode: "qa" },
  { code: "KWD", name: "KUWAITI DINAR", flag: "🇰🇼", countryCode: "kw" },
  { code: "BHD", name: "BAHRAINI DINAR", flag: "🇧🇭", countryCode: "bh" },
  { code: "OMR", name: "OMANI RIAL", flag: "🇴🇲", countryCode: "om" },
  { code: "ZAR", name: "SOUTH AFRICAN RAND", flag: "🇿🇦", countryCode: "za" },
  { code: "BWP", name: "BOTSWANA PULA", flag: "🇧🇼", countryCode: "bw" },
  { code: "KES", name: "KENYAN SHILLING", flag: "🇰🇪", countryCode: "ke" },
  { code: "NGN", name: "NIGERIAN NAIRA", flag: "🇳🇬", countryCode: "ng" },
  { code: "GHS", name: "GHANAIAN CEDI", flag: "🇬🇭", countryCode: "gh" },
  { code: "TZS", name: "TANZANIAN SHILLING", flag: "🇹🇿", countryCode: "tz" },
  { code: "UGX", name: "UGANDAN SHILLING", flag: "🇺🇬", countryCode: "ug" },
  { code: "ETB", name: "ETHIOPIAN BIRR", flag: "🇪🇹", countryCode: "et" },
  { code: "EGP", name: "EGYPTIAN POUND", flag: "🇪🇬", countryCode: "eg" },
  { code: "MAD", name: "MOROCCAN DIRHAM", flag: "🇲🇦", countryCode: "ma" },
  { code: "TND", name: "TUNISIAN DINAR", flag: "🇹🇳", countryCode: "tn" },
  { code: "BRL", name: "BRAZILIAN REAL", flag: "🇧🇷", countryCode: "br" },
  { code: "MXN", name: "MEXICAN PESO", flag: "🇲🇽", countryCode: "mx" },
  { code: "ARS", name: "ARGENTINE PESO", flag: "🇦🇷", countryCode: "ar" },
  { code: "CLP", name: "CHILEAN PESO", flag: "🇨🇱", countryCode: "cl" },
  { code: "COP", name: "COLOMBIAN PESO", flag: "🇨🇴", countryCode: "co" },
  { code: "PEN", name: "PERUVIAN SOL", flag: "🇵🇪", countryCode: "pe" },
  { code: "SEK", name: "SWEDISH KRONA", flag: "🇸🇪", countryCode: "se" },
  { code: "NOK", name: "NORWEGIAN KRONE", flag: "🇳🇴", countryCode: "no" },
  { code: "DKK", name: "DANISH KRONE", flag: "🇩🇰", countryCode: "dk" },
  { code: "PLN", name: "POLISH ZLOTY", flag: "🇵🇱", countryCode: "pl" },
  { code: "CZK", name: "CZECH KORUNA", flag: "🇨🇿", countryCode: "cz" },
  { code: "HUF", name: "HUNGARIAN FORINT", flag: "🇭🇺", countryCode: "hu" },
  { code: "RON", name: "ROMANIAN LEU", flag: "🇷🇴", countryCode: "ro" },
  { code: "TRY", name: "TURKISH LIRA", flag: "🇹🇷", countryCode: "tr" },
  { code: "RUB", name: "RUSSIAN RUBLE", flag: "🇷🇺", countryCode: "ru" },
  { code: "THB", name: "THAI BAHT", flag: "🇹🇭", countryCode: "th" },
  { code: "SGD", name: "SINGAPORE DOLLAR", flag: "🇸🇬", countryCode: "sg" },
  { code: "MYR", name: "MALAYSIAN RINGGIT", flag: "🇲🇾", countryCode: "my" },
  { code: "IDR", name: "INDONESIAN RUPIAH", flag: "🇮🇩", countryCode: "id" },
  { code: "PHP", name: "PHILIPPINE PESO", flag: "🇵🇭", countryCode: "ph" },
  { code: "VND", name: "VIETNAMESE DONG", flag: "🇻🇳", countryCode: "vn" },
  { code: "KRW", name: "SOUTH KOREAN WON", flag: "🇰🇷", countryCode: "kr" },
  { code: "TWD", name: "TAIWAN DOLLAR", flag: "🇹🇼", countryCode: "tw" },
  { code: "HKD", name: "HONG KONG DOLLAR", flag: "🇭🇰", countryCode: "hk" },
  { code: "PKR", name: "PAKISTANI RUPEE", flag: "🇵🇰", countryCode: "pk" },
  { code: "BDT", name: "BANGLADESHI TAKA", flag: "🇧🇩", countryCode: "bd" },
  { code: "LKR", name: "SRI LANKAN RUPEE", flag: "🇱🇰", countryCode: "lk" },
  { code: "MMK", name: "MYANMAR KYAT", flag: "🇲🇲", countryCode: "mm" },
  { code: "ILS", name: "ISRAELI SHEKEL", flag: "🇮🇱", countryCode: "il" },
  { code: "JOD", name: "JORDANIAN DINAR", flag: "🇯🇴", countryCode: "jo" },
  { code: "LBP", name: "LEBANESE POUND", flag: "🇱🇧", countryCode: "lb" },
  { code: "IQD", name: "IRAQI DINAR", flag: "🇮🇶", countryCode: "iq" },
  { code: "IRR", name: "IRANIAN RIAL", flag: "🇮🇷", countryCode: "ir" },
];
